spring:
  mustache:
    suffix: .html
    expose-session-attributes: true
  
  datasource:
    url: jdbc:h2:~/i-am-jwpark;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    
  mvc:
    hiddenmethod:
      filter:
        enabled: true 