spring:
  mustache:
    suffix: .html
    expose-session-attributes: true # Session에 담긴 데이터를 모델에 담아서 템플릿 엔진에 전달해주는 설정.
  
  datasource:
    url: jdbc:h2:~/i-am-jwpark;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true # 실행할 때, 쿼리 보여주기.
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    
  mvc:
    hiddenmethod:
      filter:
        enabled: true