
INSERT INTO USER (SEQ, USER_ID, PASSWORD, NAME, EMAIL, CREATED_DATE) VALUES (1, 'jwpark01', 'jw01' , '재원01', 'jw01@naver', CURRENT_TIMESTAMP());
INSERT INTO USER (SEQ, USER_ID, PASSWORD, NAME, EMAIL, CREATED_DATE) VALUES (2, 'jwpark99', 'jw99' , '재원99', 'jw99@naver', CURRENT_TIMESTAMP());

INSERT INTO QUESTION (SEQ, WRITER_SEQ, TITLE, CONTENTS, COUNT_OF_ANSWER, CREATED_DATE) VALUES (1, 1, 'SAMPLE TITLE', 'SAMPLE CONTENTS', 0, CURRENT_TIMESTAMP());