INSERT INTO USER (USER_ID, PASSWORD, NAME, EMAIL) VALUES ('jwpark01', 'jw01' , '재원01', 'jw01@naver');
INSERT INTO USER (USER_ID, PASSWORD, NAME, EMAIL) VALUES ('jwpark99', 'jw99' , '재원99', 'jw99@naver');

-- INSERT INTO USER (SEQ, USER_ID, PASSWORD, NAME, EMAIL) VALUES (1, 'jwpark01', 'jw01' , '재원01', 'jw01@naver');
-- INSERT INTO USER (SEQ, USER_ID, PASSWORD, NAME, EMAIL) VALUES (2, 'jwpark99', 'jw99' , '재원99', 'jw99@naver');

-- INSERT INTO QUESTION (SEQ, WRITER_SEQ, TITLE, CONTENTS, CREATE_DATE) VALUES (1, 1, 'SAMPLE TITLE', 'SAMPLE CONTENTS', CURRENT_TIMESTAMP());